name             'picturepress'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures picturepress'
long_description 'Installs/Configures picturepress'
version          '0.1.0'

depends 'rbenv', '~> 1.7.1'
depends 'postfix', '~> 3.6.2'
depends 'postgresql', '~> 3.4.14'
depends 'nginx', '~> 2.7.4'
